# Server port for user service 8081
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

  show-sql: true
